### ISSUE TITLE
May you ship a license with this?

### ISSUE THREAD

**Issue by MrDini123** [FraserChapman/cache#1]
Good day,

I figured that this little script would be very useful for me to use in my addons however in its current state I cannot include these in my AGPL3 licensed project. Is it intended to remain all rights reserved or by any chance would you mind adding a license that allows reusing? Would be incredibly awesome!

Thanks

**Comment by FraserChapman** [comment]
Sure I've popped an MIT licence on it: https://github.com/FraserChapman/cache/blob/master/LICENSE.txt

You might also what to look how this is actually implemented in one of my add-ons (e.g. https://github.com/FraserChapman/plugin.video.iwm/blob/master/resources/lib/cache.py and https://github.com/FraserChapman/plugin.video.iwm/blob/master/resources/lib/search.py) as there are a couple of extra imports and tweaks so that it automatically generates the sqlite DB in the add-on data folder for Kodi. 

Also I am in the process of making it a "script.module" so that it can be included directly from Kodi with these changes.

Thanks for the interest, hope it is useful for you.

**Comment by MrDini123** [comment]
Great, I'll take a deeper look in your implementation also. Thank you for all your efforts.

And since caching is something I'd use regularly in most of my addons, I'd ship this module as a part of my common routines script. Certainly with crediting.

**Comment by FraserChapman** [comment]
Hey - this is now in a open PR to go into the script repo for kodi: https://github.com/xbmc/repo-scripts/pull/1084

I have updated and added a couple of things: https://github.com/FraserChapman/script.module.cache

You should probably wait on using this until it is added - then you will be able to simply use it as a dependancy via any addon.xml

e.g.   `<import addon="script.module.cache" version="1.0.0"/>`

**Comment by MrDini123** [comment]
Oh wow you've really done a great job, thanks!

**Comment by FraserChapman** [comment]
> Oh wow you've really done a great job, thanks!

Many thanks - this is now an included in Kodi - [script.module.cache](https://mirrors.kodi.tv/addons/leia/script.module.cache/)

That said there is a tiny bug in v1.0.0 with the Store class :( - so please use 1.0.1 when it gets merged.

e.g. `<import addon="script.module.cache" version="1.0.1"/> `
